LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)


# $(warning LOCAL_PATH='$(LOCAL_PATH)')
# $(warning BUILD_SHARED_LIBRARY='$(BUILD_SHARED_LIBRARY)')
# $(warning TOP='$(TOP)')
# $(warning RTK_FRAMEWORKS_NATIVE_PATH='$(RTK_FRAMEWORKS_NATIVE_PATH)')

$(info Building boost ...)
$(info Toolchain Prefix='$(TARGET_TOOLS_PREFIX)')
result := $(shell $(LOCAL_PATH)/build_boost_lib.sh $(LOCAL_PATH)/ $(LOCAL_PATH)/)


############################################
include $(CLEAR_VARS)
LOCAL_MODULE := libboost_thread
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_thread.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_graph
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_graph.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := libboost_math_c99f
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_math_c99f.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_math_c99
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_math_c99.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_log
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_log.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := libboost_wave
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_wave.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_unit_test_framework
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_unit_test_framework.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_signals
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_signals.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := libboost_math_c99l
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_math_c99l.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := libboost_filesystem
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_filesystem.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_random
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_random.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := libboost_math_tr1
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_math_tr1.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_wserialization
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_wserialization.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := libboost_program_options
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_program_options.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_atomic
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_atomic.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_iostreams
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_iostreams.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_prg_exec_monitor
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_prg_exec_monitor.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_math_tr1l
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_math_tr1l.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_container
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_container.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_timer
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_timer.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_regex
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_regex.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_date_time
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_date_time.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_math_tr1f
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_math_tr1f.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_locale
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_locale.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_log_setup
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_log_setup.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_chrono
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_chrono.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_system
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_system.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_serialization
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_serialization.so.1.57.0
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := libboost_exception
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_exception.a
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libboost_test_exec_monitor
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/
LOCAL_SRC_FILES := bin/lib/libboost_test_exec_monitor.a
LOCAL_MULTILIB := 32
LOCAL_EXPORT_C_INCLUDES := bin/include
include $(BUILD_PREBUILT)

